version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    ignore:
      - dependency-name: "com.microsoft.sqlserver*"
      - dependency-name: "com.oracle.database.jdbc*"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: weekly
      day: "friday"
    open-pull-requests-limit: 20

  - package-ecosystem: nuget
    directory: "/net"
    ignore:
      - dependency-name: "Microsoft.Data.SQLite"
    schedule:
      interval: weekly
      day: "friday"
    open-pull-requests-limit: 20

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: "friday"
    open-pull-requests-limit: 20
