version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    #avoids loback 1.4 to keep compatibility with java 8
    ignore:
      - dependency-name: "ch.qos.logback*"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "com.microsoft.sqlserver*"
      - dependency-name: "com.oracle.database.jdbc*"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: weekly
      day: "friday"
    open-pull-requests-limit: 20

  - package-ecosystem: nuget
    directory: "/net"
    #avoids updates that cause not compilable code
    ignore:
      - dependency-name: "RestSharp"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.Data.SQLite"
    schedule:
      interval: weekly
      day: "friday"
    open-pull-requests-limit: 20

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: "friday"
    open-pull-requests-limit: 20
