name: Publish to Maven and NuGet
on:
  release:
    types: [created]
jobs:
  release-java:
    #if: ${{ false }}  # disable for now
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      #Official documentation seems incomplete. To avoid failure when importing key: 
      #https://stackoverflow.com/questions/61096521/how-to-use-gpg-key-in-github-actions
      #It requires export the private key with the armor option: gpg --output private.pgm --armor --export-secret-key <email>
      - name: Import GPG Key 
        uses: crazy-max/ghaction-import-gpg@v5.3.0
        with:
          gpg_private_key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

# uncomment to activate publish
#      - name: Set up Apache Maven Central
#        uses: actions/setup-java@v3
#        with: # running setup-java again overwrites the settings.xml
#          distribution: 'temurin'
#          java-version: '8'
#          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
#          server-username: MAVEN_USERNAME # env variable for username in deploy
#          server-password: MAVEN_CENTRAL_TOKEN # env variable for token in deploy
#          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
#          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase

# uncomment to activate publish
#      - name: Publish to Apache Maven Central
#        run: mvn deploy -P publish-maven -DskipTests=true -Dmaven.test.failure.ignore=true -U --no-transfer-progress
#        env:
#          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
#          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
#          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

